from rl.core import Processor

class MCMLProcessor(Processor):
    def __init__(self):
        ...
    def process_step(self, observation, reward, done, info):
        ...
    def process_action(self, action):
        ...
    def process_info(self, info):
        ...
    def process_observation(self, observation):
        ...
    def process_reward(self, reward):
        ...
    def process_state_batch(self, batch):
        ...
