from rl.core import Processor

class AVProcessor(Processor):
    def __init__(self):
        ...
    def process_action(self, action):
        ...
    def process_observation(self, observation):
        ...
    def process_reward(self, reward):
        ...
